#!/usr/bin/env node
// SPDX-License-Identifier: LicenseRef-PolyForm-Strict-1.0.0
// Copyright (c) 2025–2026 Christopher Chen
//
// scripts/emit-stats.mjs
//
// Emits src/generated/stats.js at build time with live counts for:
//   - TESTS_DISPLAY: pytest --collect-only count, floored to nearest 100
//   - CHECKS_DISPLAY: CHECKS.md row count (excluding † informational rows),
//                    summed across US / CN / TW, floored to nearest 5
//
// Consumed by src/pages/AboutPage.jsx (StatsGrid) so the "+ automated tests"
// and "+ drafting checks" stat cards auto-update without manual edits.
//
// Called from `npm run build` between build:wheel and build:version.
//
// Graceful-fallback philosophy: if pytest collect fails (e.g. Python env
// missing during `vite build --mode preview`), keep the prior generated
// numbers rather than regressing to zero. The file is committed, so a
// failed regeneration means the stale-but-sensible values stay.

import { execSync } from 'child_process'
import { existsSync, readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '..', '..')
const checksMdPath = join(repoRoot, 'CHECKS.md')
const outPath = join(__dirname, '..', 'src', 'generated', 'stats.js')

const floorTo = (n, step) => Math.floor(n / step) * step

function countChecks() {
  if (!existsSync(checksMdPath)) {
    throw new Error(`CHECKS.md not found at ${checksMdPath}`)
  }
  const text = readFileSync(checksMdPath, 'utf-8')
  // Section header → jurisdiction classification. The document layout
  // groups checks into jurisdiction-specific sections; rows in each
  // section are `| Check name | ... |` table rows. Rows marked with †
  // are informational-only (summary tiles, not failure checks) and are
  // excluded from the count.
  const JUR_BY_HEADER = {
    Specification: 'US',
    Claims: 'US',
    'Brief Description of Drawings': 'US',
    Abstract: 'US',
    'CN Specification': 'CN',
    'CN Claims': 'CN',
    'CN Abstract': 'CN',
    'CN Drawings': 'CN',
    'TW Specification': 'TW',
    'TW Claims': 'TW',
    'TW Abstract': 'TW',
    'TW Cross-Reference': 'TW',
    'TW Drawings': 'TW',
    'EPC Specification': 'EPC',
    'EPC Claims': 'EPC',
    'EPC Abstract': 'EPC',
    'EPC Drawings': 'EPC',
  }
  const counts = { US: 0, CN: 0, TW: 0, EPC: 0 }
  let current = null
  for (const line of text.split('\n')) {
    const headerMatch = line.match(/^## (.+?)(?:\s*\(.*\))?$/)
    if (headerMatch) {
      current = JUR_BY_HEADER[headerMatch[1].trim()] ?? null
      continue
    }
    if (!current) continue
    if (!line.startsWith('|')) continue
    const cols = line.split('|').map((c) => c.trim())
    if (cols.length < 3) continue
    const first = cols[1]
    if (!first || first.startsWith('-') || first === 'Check') continue
    if (first.includes('†')) continue
    counts[current] += 1
  }
  const total = counts.US + counts.CN + counts.TW + counts.EPC
  return { total, perJurisdiction: counts }
}

function countTests() {
  try {
    // --collect-only -q prints one line per test, plus a trailing
    // summary line like "1955 tests collected". Parse the summary.
    const out = execSync('python3 -m pytest --collect-only -q 2>/dev/null', {
      cwd: repoRoot,
      encoding: 'utf-8',
    })
    const summary = out.match(/(\d+)\s+tests?\s+collected/i)
    if (summary) {
      return parseInt(summary[1], 10)
    }
    // Fallback: count "::" lines (each is one collected test id).
    const lines = out.split('\n').filter((l) => l.includes('::'))
    return lines.length
  } catch (e) {
    console.warn('[emit-stats] pytest collect failed; preserving prior value')
    return null
  }
}

// Read any existing generated file so we can preserve values on failure.
function readPriorStats() {
  if (!existsSync(outPath)) return null
  const src = readFileSync(outPath, 'utf-8')
  const tRaw = src.match(/TESTS_RAW\s*=\s*(\d+)/)
  const tDisplay = src.match(/TESTS_DISPLAY\s*=\s*(\d+)/)
  const cRaw = src.match(/CHECKS_RAW\s*=\s*(\d+)/)
  const cDisplay = src.match(/CHECKS_DISPLAY\s*=\s*(\d+)/)
  return {
    testsRaw: tRaw ? parseInt(tRaw[1], 10) : null,
    testsDisplay: tDisplay ? parseInt(tDisplay[1], 10) : null,
    checksRaw: cRaw ? parseInt(cRaw[1], 10) : null,
    checksDisplay: cDisplay ? parseInt(cDisplay[1], 10) : null,
  }
}

const prior = readPriorStats()

const { total: checksRaw, perJurisdiction } = countChecks()
const checksDisplay = floorTo(checksRaw, 5)

const testsRaw = countTests()
const resolvedTestsRaw = testsRaw ?? prior?.testsRaw ?? 0
const testsDisplay =
  testsRaw !== null ? floorTo(testsRaw, 100) : prior?.testsDisplay ?? 0

const contents = `// SPDX-License-Identifier: LicenseRef-PolyForm-Strict-1.0.0
// Copyright (c) 2025–2026 Christopher Chen
// AUTO-GENERATED by frontend/scripts/emit-stats.mjs — do not edit by hand.
// Regenerated at build time from pytest --collect-only and CHECKS.md.
//
// TESTS_DISPLAY: pytest count floored to nearest 100 (for the "+ tests" card).
// CHECKS_DISPLAY: CHECKS.md row count floored to nearest 5 (for the "+ checks" card).
// RAW values are kept for reference / telemetry / tests.

export const TESTS_RAW = ${resolvedTestsRaw}
export const TESTS_DISPLAY = ${testsDisplay}
export const CHECKS_RAW = ${checksRaw}
export const CHECKS_DISPLAY = ${checksDisplay}
export const CHECKS_BY_JURISDICTION = ${JSON.stringify(perJurisdiction)}
`

writeFileSync(outPath, contents)
console.log(
  `[emit-stats] tests=${resolvedTestsRaw} → ${testsDisplay}   checks=${checksRaw} → ${checksDisplay}   (per-jur ${JSON.stringify(perJurisdiction)})`,
)
